name: Publish to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.4.2

      - name: Publish
        run: ./gradlew publish -PreleaseVersion=${{ github.event.inputs.version }}
        env:
          GH_PACKAGES_RW_TOKEN: ${{ secrets.GH_PACKAGES_RW_TOKEN }}
